# This formula is auto-generated by GoReleaser on each release.
# This local copy is for development/testing only.
# The canonical version lives in AutobahnSecurity/homebrew-tap.

class EamCollector < Formula
  desc "AI usage collector agent for Enterprise Agent Management"
  homepage "https://github.com/AutobahnSecurity/eam-collector"
  license :cannot_represent
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v#{version}/eam-collector-#{version}-darwin-arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
    on_intel do
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v#{version}/eam-collector-#{version}-darwin-amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v#{version}/eam-collector-#{version}-linux-arm64.tar.gz"
      sha256 "PLACEHOLDER"
    end
    on_intel do
      url "https://github.com/AutobahnSecurity/eam-collector/releases/download/v#{version}/eam-collector-#{version}-linux-amd64.tar.gz"
      sha256 "PLACEHOLDER"
    end
  end

  def install
    bin.install "eam-collector"
    etc.install "config.example.yaml" => "eam-collector/config.example.yaml"
  end

  def post_install
    config_dir = Pathname.new("#{Dir.home}/.eam-collector")
    config_dir.mkpath
    config_file = config_dir/"config.yaml"
    unless config_file.exist?
      cp etc/"eam-collector/config.example.yaml", config_file
      ohai "Config template created at #{config_file}"
      ohai "Edit it with your server URL and API key before starting the service"
    end
  end

  service do
    run [opt_bin/"eam-collector"]
    keep_alive true
    log_path var/"log/eam-collector.log"
    error_log_path var/"log/eam-collector.log"
  end

  def caveats
    <<~EOS
      To get started:

        1. Edit your config with your EAM server URL and API key:
           nano ~/.eam-collector/config.yaml

        2. Start the background daemon:
           brew services start eam-collector

        3. Check logs:
           tail -f #{var}/log/eam-collector.log
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/eam-collector --version")
  end
end
